version: '3.8'

services:

  client:
    image: alligator_client
    command: npm run dev
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - web

  web:
    build: .
    #command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    command: poetry run uvicorn alligator.api.__init__:create_app --factory --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/alligator
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION_STRING=mongodb://admin:password@mongo:27017/
    restart: always
    depends_on:
      - mongo
      - mongo-express

  event-loader:
    image: alligator_event-loader
    command: poetry run python3 event_loader/scheduler.py
    ports:
      - "8008:8008"
    environment:
      - DB_CONNECTION_STRING=mongodb://admin:password@mongo:27017/
    restart: always
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=alligator_mongo
    depends_on:
      - mongo
